// modal
export const UPDATE_SHOW_MODAL = "UPDATE_SHOW_MODAL";
// accordion
export const UPDATE_IS_OPEN = "UPDATE_IS_OPEN";
// sorting
export const UPDATE_SELECTED_TYPES = "UPDATE_SELECTED_TYPES";
export const UPDATE_SELECTED_REGIONS = "UPDATE_SELECTED_REGIONS";
// cursor
export const UPDATE_IS_OVER_CARD = "UPDATE_IS_OVER_CARD";
// pokemon
export const UPDATE_SEARCHED_POKEMON = "UPDATE_SEARCHED_POKEMON";
export const UPDATE_SELECTED_POKEMON = "UPDATE_SELECTED_POKEMON";
export const SET_SELECTED_POKEMON = "SET_SELECTED_POKEMON";
export const SET_ALL_POKEMONS = "SET_ALL_POKEMONS";
export const ADD_POKEMON = "ADD_POKEMON";
export const GET_POKEMONS = "GET_POKEMONS";
export const UPDATE_FILTERED_POKEMONS = "UPDATE_FILTERED_POKEMONS";
