export const UPDATE_IS_OPEN = "UPDATE_IS_OPEN";
export const UPDATE_SELECTED_TYPES = "UPDATE_SELECTED_TYPES";
export const UPDATE_SELECTED_REGIONS = "UPDATE_SELECTED_REGIONS";
export const UPDATE_IS_OVER_CARD = "UPDATE_IS_OVER_CARD";
